name: fetch free ss

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # 使用Python 3版本

      - name: Install dependencies
        run: |
          pip install pyaes
          pip install requests

      - name: Run Python script
        run: |
          python -c "
import requests
import base64
import json
import pyaes
import binascii

def f(g, d, e):
    h = pyaes.AESModeOfOperationCBC(d, iv=e)
    i = b''.join(h.decrypt(g[j:j+16]) for j in range(0, len(g), 16))
    return i[:-i[-1]]

a = 'http://api.skrapp.net/api/serverlist'
b = {
    'accept': '/',
    'accept-language': 'zh-Hans-CN;q=1, en-CN;q=0.9',
    'appversion': '1.3.1',
    'user-agent': 'SkrKK/1.3.1 (iPhone; iOS 13.5; Scale/2.00)',
    'content-type': 'application/x-www-form-urlencoded',
    'Cookie': 'PHPSESSID=fnffo1ivhvt0ouo6ebqn86a0d4'
}
c = {'data': '4265a9c353cd8624fd2bc7b5d75d2f18b1b5e66ccd37e2dfa628bcb8f73db2f14ba98bc6a1d8d0d1c7ff1ef0823b11264d0addaba2bd6a30bdefe06f4ba994ed'}
d = b'65151f8d966bf596'
e = b'88ca0f0ea1ecf975'

j = requests.post(a, headers=b, data=c)

if j.status_code == 200:
    k = j.text.strip()
    l = binascii.unhexlify(k)
    m = f(l, d, e)
    n = json.loads(m)
    with open('ss.txt', 'w') as file:
        for o in n['data']:
            p = f'aes-256-cfb:{o['password']}@{o['ip']}:{o['port']}'
            q = base64.b64encode(p.encode('utf-8')).decode('utf-8')
            r = f'ss://{q}#{o['title']}'
            file.write(r + '\n')
          "

      - name: Commit and Push ss.txt
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ss.txt
          git commit -m "Update ss.txt"
          git push
